name: jest
on: 
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      - name: Enable Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'
      - run: npm install
      - run: npm run test-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
          fail_ci_if_error: true
          override_branch: ${{github.base_ref}}	