name: jest-test
on: 
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Enable Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'
      - run: npm install
      - run: npm run test